# Generated by Django 4.1.7 on 2023-03-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('anons', models.CharField(max_length=250, verbose_name='Preview')),
                ('full_article', models.TextField(verbose_name='Full Article')),
                ('date', models.DateTimeField(verbose_name='Publish Date')),
            ],
        ),
    ]
