# Generated by Django 4.1.7 on 2023-03-13 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'New', 'verbose_name_plural': 'News'},
        ),
    ]
