# Generated by Django 4.1.7 on 2023-03-27 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_of_birth', models.DateField(blank=True, null=True)),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='images/profile/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='images/profile/')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='images/profile/')),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='images/profile/')),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to='images/profile/')),
                ('facebook', models.TextField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
