# Generated by Django 4.1.7 on 2023-03-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='facebook',
            new_name='description',
        ),
        migrations.AddField(
            model_name='profile',
            name='telegramm',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
