# Generated by Django 4.1.7 on 2023-03-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_facebook_profile_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telegramm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
