# Generated by Django 4.1.7 on 2023-04-01 03:40

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_telegramm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Полное описание'),
        ),
    ]
