# Generated by Django 4.1.7 on 2023-04-10 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_profile_dislikes_profile_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
