# Generated by Django 4.1.7 on 2023-04-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_profile_likes_remove_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='premium',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
    ]
