# Generated by Django 4.1.7 on 2023-04-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='profile_avatars'),
        ),
    ]
