# Generated by Django 4.1.7 on 2023-04-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='premium',
            field=models.ImageField(default='none_status.png', upload_to='profile_avatars'),
        ),
    ]
