# Generated by Django 4.1.7 on 2023-03-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'New', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review',
            field=models.TextField(verbose_name='Your review'),
        ),
    ]
