# Generated by Django 4.1.7 on 2023-03-29 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_reviews_options_alter_reviews_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Reviews', 'verbose_name_plural': 'Reviews'},
        ),
    ]
